// <auto-generated />
using System;
using HorseRacing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HorseRacing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HorseRacingDbContext))]
    [Migration("20261009072605_AddRaceResultsWorkQueue")]
    partial class AddRaceResultsWorkQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateOnly>("FoaledOn")
                        .HasColumnType("date")
                        .HasColumnName("foaled_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_horses");

                    b.HasIndex("Name", "FoaledOn", "CountryCode")
                        .HasDatabaseName("ix_horses_identity");

                    b.ToTable("horses", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Jockey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("licence_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_jockeys");

                    b.HasIndex("CountryCode", "LicenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_jockeys_licence_number");

                    b.ToTable("jockeys", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RacecourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("racecourse_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_meetings");

                    b.HasIndex("RacecourseId", "ScheduledDate", "Name")
                        .HasDatabaseName("ix_meetings_racecourse_date_name");

                    b.ToTable("meetings", null, t =>
                        {
                            t.HasCheckConstraint("ck_meetings_status", "status IN ('Scheduled', 'InProgress', 'Completed', 'Abandoned')");

                            t.HasCheckConstraint("ck_meetings_type", "type IN ('Flat', 'Jump', 'Mixed')");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_owners");

                    b.HasIndex("DisplayName", "Type", "CountryCode")
                        .HasDatabaseName("ix_owners_identity");

                    b.ToTable("owners", null, t =>
                        {
                            t.HasCheckConstraint("ck_owners_type", "type IN ('Individual', 'Partnership', 'Syndicate', 'Company', 'RacingClub')");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<int>("DistanceMetres")
                        .HasColumnType("integer")
                        .HasColumnName("distance_metres");

                    b.Property<string>("GoingDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("going_description");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("race_number");

                    b.Property<DateTimeOffset>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("surface");

                    b.HasKey("Id")
                        .HasName("pk_races");

                    b.HasIndex("MeetingId", "RaceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_races_meeting_race_number");

                    b.HasIndex("MeetingId", "ScheduledStartUtc")
                        .HasDatabaseName("ix_races_meeting_start");

                    b.ToTable("races", null, t =>
                        {
                            t.HasCheckConstraint("ck_races_code", "code IN ('Flat', 'Hurdle', 'Steeplechase', 'NationalHuntFlat')");

                            t.HasCheckConstraint("ck_races_numbers", "race_number > 0 AND distance_metres > 0");

                            t.HasCheckConstraint("ck_races_status", "status IN ('Scheduled', 'Off', 'Finished', 'Abandoned')");

                            t.HasCheckConstraint("ck_races_surface", "surface IN ('Turf', 'AllWeather')");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<TimeSpan?>("WinningTime")
                        .HasColumnType("interval")
                        .HasColumnName("winning_time");

                    b.HasKey("Id")
                        .HasName("pk_race_results");

                    b.HasAlternateKey("Id", "RaceId")
                        .HasName("ak_race_results_id_race_id");

                    b.HasIndex("RaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_race_results_race_id");

                    b.ToTable("race_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_race_results_status", "status IN ('Provisional', 'Official')");

                            t.HasCheckConstraint("ck_race_results_time", "winning_time IS NULL OR winning_time > interval '0 seconds'");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Racecourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_racecourses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_racecourses_name");

                    b.ToTable("racecourses", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CarriedWeightPounds")
                        .HasColumnType("integer")
                        .HasColumnName("carried_weight_pounds");

                    b.Property<int>("ClothNumber")
                        .HasColumnType("integer")
                        .HasColumnName("cloth_number");

                    b.Property<decimal?>("DeclaredOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("declared_odds");

                    b.Property<int?>("Draw")
                        .HasColumnType("integer")
                        .HasColumnName("draw");

                    b.Property<Guid>("HorseId")
                        .HasColumnType("uuid")
                        .HasColumnName("horse_id");

                    b.Property<Guid?>("JockeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("jockey_id");

                    b.Property<string>("NonRunnerReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("non_runner_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<Guid?>("StableId")
                        .HasColumnType("uuid")
                        .HasColumnName("stable_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_id");

                    b.HasKey("Id")
                        .HasName("pk_runners");

                    b.HasAlternateKey("Id", "RaceId")
                        .HasName("ak_runners_id_race_id");

                    b.HasIndex("HorseId")
                        .HasDatabaseName("ix_runners_horse_id");

                    b.HasIndex("JockeyId")
                        .HasDatabaseName("ix_runners_jockey_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_runners_owner_id");

                    b.HasIndex("StableId");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("ix_runners_trainer_id");

                    b.HasIndex("RaceId", "ClothNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_runners_race_cloth_number");

                    b.HasIndex("RaceId", "Draw")
                        .IsUnique()
                        .HasDatabaseName("ux_runners_race_draw")
                        .HasFilter("draw IS NOT NULL");

                    b.HasIndex("RaceId", "HorseId")
                        .IsUnique()
                        .HasDatabaseName("ux_runners_race_horse");

                    b.ToTable("runners", null, t =>
                        {
                            t.HasCheckConstraint("ck_runners_numbers", "cloth_number > 0 AND (draw IS NULL OR draw > 0) AND (carried_weight_pounds IS NULL OR carried_weight_pounds > 0)");

                            t.HasCheckConstraint("ck_runners_odds", "declared_odds IS NULL OR declared_odds > 1");

                            t.HasCheckConstraint("ck_runners_status", "(status = 'Declared' AND non_runner_reason IS NULL) OR (status = 'NonRunner' AND length(trim(non_runner_reason)) > 0 AND non_runner_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RunnerResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("DistanceBeatenLengths")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("distance_beaten_lengths");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer")
                        .HasColumnName("finish_position");

                    b.Property<bool>("IsDeadHeat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead_heat");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<decimal?>("PrizeMoney")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("prize_money");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<Guid>("RaceResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_result_id");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("runner_id");

                    b.Property<decimal?>("StartingPriceDecimal")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("starting_price_decimal");

                    b.HasKey("Id")
                        .HasName("pk_runner_results");

                    b.HasIndex("RunnerId")
                        .IsUnique()
                        .HasDatabaseName("ux_runner_results_runner_id");

                    b.HasIndex("RaceResultId", "FinishPosition")
                        .HasDatabaseName("ix_runner_results_result_finish_position");

                    b.HasIndex("RaceResultId", "RaceId");

                    b.HasIndex("RunnerId", "RaceId")
                        .IsUnique();

                    b.ToTable("runner_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_runner_results_outcome", "outcome IN ('Finished', 'PulledUp', 'Fell', 'UnseatedRider', 'Refused', 'BroughtDown', 'RanOut', 'Disqualified', 'Void')");

                            t.HasCheckConstraint("ck_runner_results_position", "(outcome = 'Finished' AND finish_position IS NOT NULL AND finish_position > 0) OR (outcome <> 'Finished' AND finish_position IS NULL AND NOT is_dead_heat)");

                            t.HasCheckConstraint("ck_runner_results_values", "(distance_beaten_lengths IS NULL OR distance_beaten_lengths >= 0) AND (starting_price_decimal IS NULL OR starting_price_decimal > 1) AND (prize_money IS NULL OR prize_money >= 0)");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Stable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("town");

                    b.HasKey("Id")
                        .HasName("pk_stables");

                    b.HasIndex("Name", "Town", "CountryCode")
                        .HasDatabaseName("ix_stables_identity");

                    b.ToTable("stables", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("licence_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("StableId")
                        .HasColumnType("uuid")
                        .HasColumnName("stable_id");

                    b.HasKey("Id")
                        .HasName("pk_trainers");

                    b.HasIndex("StableId")
                        .HasDatabaseName("ix_trainers_stable_id");

                    b.HasIndex("CountryCode", "LicenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_trainers_licence_number");

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Curated.CuratedDomainObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_name");

                    b.Property<string>("DomainObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain_object_type");

                    b.Property<DateTimeOffset>("FirstObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_observed_at_utc");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<Guid>("LastPromotionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_promotion_run_id");

                    b.Property<Guid>("RawCollectionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_collection_run_id");

                    b.Property<Guid>("RawPayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_payload_id");

                    b.Property<string>("SourceDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_data");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.HasIndex("LastPromotionRunId")
                        .HasDatabaseName("ix_curated_domain_objects_last_promotion_run_id");

                    b.HasIndex("RawCollectionRunId")
                        .HasDatabaseName("ix_curated_domain_objects_raw_collection_run_id");

                    b.HasIndex("RawPayloadId")
                        .HasDatabaseName("ix_curated_domain_objects_raw_payload_id");

                    b.HasIndex("DomainObjectType", "DisplayName")
                        .HasDatabaseName("ix_curated_domain_objects_type_display_name");

                    b.HasIndex("SourceSystem", "DomainObjectType", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ux_curated_domain_objects_source_identity");

                    b.ToTable("domain_objects", "curated", t =>
                        {
                            t.HasCheckConstraint("ck_curated_domain_objects_observation_dates", "last_observed_at_utc >= first_observed_at_utc");

                            t.HasCheckConstraint("ck_curated_domain_objects_source_data_json", "jsonb_typeof(source_data) = 'object'");
                        });
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Curated.CuratedPromotionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_sha256")
                        .IsFixedLength();

                    b.Property<string>("PromoterVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("promoter_version");

                    b.Property<Guid>("RawCollectionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_collection_run_id");

                    b.Property<Guid>("RawPayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_payload_id");

                    b.Property<int>("RecordsFound")
                        .HasColumnType("integer")
                        .HasColumnName("records_found");

                    b.Property<int>("RecordsUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("records_upserted");

                    b.Property<string>("SourceJobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_job_name");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RawCollectionRunId")
                        .HasDatabaseName("ix_curated_promotion_runs_raw_collection_run_id");

                    b.HasIndex("RawPayloadId")
                        .IsUnique()
                        .HasDatabaseName("ux_curated_promotion_runs_running_payload")
                        .HasFilter("outcome = 'Running'");

                    b.HasIndex("RawPayloadId", "Outcome")
                        .HasDatabaseName("ix_curated_promotion_runs_raw_payload_outcome");

                    b.HasIndex("SourceJobName", "StartedAtUtc")
                        .HasDatabaseName("ix_curated_promotion_runs_source_job_started");

                    b.ToTable("promotion_runs", "curated", t =>
                        {
                            t.HasCheckConstraint("ck_curated_promotion_runs_completion", "(outcome = 'Running' AND completed_at_utc IS NULL) OR (outcome <> 'Running' AND completed_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_curated_promotion_runs_outcome", "outcome IN ('Running', 'Succeeded', 'Skipped', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("ck_curated_promotion_runs_record_counts", "records_found >= 0 AND records_upserted >= 0");
                        });
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Raw.RaceResultsWorkQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DispatchItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dispatch_item_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_name");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error_message");

                    b.Property<int?>("LastHttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("last_http_status_code");

                    b.Property<Guid?>("LastRawCollectionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_raw_collection_run_id");

                    b.Property<Guid?>("LastRawPayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_raw_payload_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("work_type");

                    b.HasKey("Id");

                    b.HasIndex("DispatchItemId", "JobName", "SourceUrl")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_result_work_queue_dispatch_job_source");

                    b.HasIndex("DispatchItemId", "Status", "AvailableAtUtc", "Priority", "CreatedAtUtc")
                        .HasDatabaseName("ix_raw_result_work_queue_claim");

                    b.ToTable("result_work_queue", "raw", t =>
                        {
                            t.HasCheckConstraint("ck_raw_result_work_queue_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_raw_result_work_queue_status", "status IN ('Pending', 'Running', 'Succeeded', 'Unavailable', 'Failed')");
                        });
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CollectorVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("collector_version");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("DispatchItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dispatch_item_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DispatchItemId", "Outcome")
                        .HasDatabaseName("ix_raw_collection_runs_dispatch_outcome");

                    b.HasIndex("JobName", "SourceUrl")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_collection_runs_running_source")
                        .HasFilter("outcome = 'Running'");

                    b.HasIndex("SourceUrl", "StartedAtUtc")
                        .HasDatabaseName("ix_raw_collection_runs_source_started");

                    b.ToTable("collection_runs", "raw", t =>
                        {
                            t.HasCheckConstraint("ck_raw_collection_runs_completion", "(outcome = 'Running' AND completed_at_utc IS NULL) OR (outcome <> 'Running' AND completed_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_raw_collection_runs_outcome", "outcome IN ('Running', 'Succeeded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CharacterEncoding")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("character_encoding");

                    b.Property<Guid>("CollectionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_run_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<string>("EffectiveUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("effective_url");

                    b.Property<string>("EntityTag")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_tag");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<DateTimeOffset?>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_utc");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("media_type");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at_utc");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.HasIndex("CollectionRunId")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_payloads_collection_run");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_raw_payloads_sha256");

                    b.ToTable("payloads", "raw", t =>
                        {
                            t.HasCheckConstraint("ck_raw_payloads_content_length", "content_length = octet_length(content)");

                            t.HasCheckConstraint("ck_raw_payloads_http_status_code", "http_status_code BETWEEN 100 AND 599");

                            t.HasCheckConstraint("ck_raw_payloads_sha256", "sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Weather.CuratedRaceWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ApparentTemperatureC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("apparent_temperature_c");

                    b.Property<Guid>("CuratedRaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("curated_race_id");

                    b.Property<decimal>("PrecipitationMillimetres")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("precipitation_millimetres");

                    b.Property<DateTimeOffset>("RaceStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("race_start_utc");

                    b.Property<Guid>("RacecourseLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("racecourse_location_id");

                    b.Property<decimal>("RainMillimetres")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("rain_millimetres");

                    b.Property<Guid>("RawCollectionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_collection_run_id");

                    b.Property<Guid>("RawPayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_payload_id");

                    b.Property<int>("RelativeHumidityPercent")
                        .HasColumnType("integer")
                        .HasColumnName("relative_humidity_percent");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at_utc");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<decimal>("TemperatureC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_c");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("integer")
                        .HasColumnName("weather_code");

                    b.Property<DateTimeOffset>("WeatherHourUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("weather_hour_utc");

                    b.Property<int>("WindDirectionDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("wind_direction_degrees");

                    b.Property<decimal>("WindGustKilometresPerHour")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("wind_gust_kilometres_per_hour");

                    b.Property<decimal>("WindSpeedKilometresPerHour")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("wind_speed_kilometres_per_hour");

                    b.HasKey("Id");

                    b.HasIndex("CuratedRaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_curated_race_weather_curated_race_id");

                    b.HasIndex("RawCollectionRunId")
                        .HasDatabaseName("ix_curated_race_weather_raw_collection_run_id");

                    b.HasIndex("RawPayloadId")
                        .HasDatabaseName("ix_curated_race_weather_raw_payload_id");

                    b.HasIndex("RacecourseLocationId", "RaceStartUtc")
                        .HasDatabaseName("ix_curated_race_weather_location_start");

                    b.ToTable("race_weather", "curated", t =>
                        {
                            t.HasCheckConstraint("ck_curated_race_weather_code", "weather_code BETWEEN 0 AND 99");

                            t.HasCheckConstraint("ck_curated_race_weather_humidity", "relative_humidity_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_curated_race_weather_precipitation", "precipitation_millimetres >= 0 AND rain_millimetres >= 0");

                            t.HasCheckConstraint("ck_curated_race_weather_wind", "wind_speed_kilometres_per_hour >= 0 AND wind_gust_kilometres_per_hour >= 0 AND wind_direction_degrees BETWEEN 0 AND 360");
                        });
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Weather.CuratedRacecourseLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("course_name");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_source");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<Guid>("RawCollectionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_collection_run_id");

                    b.Property<Guid>("RawPayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_payload_id");

                    b.Property<DateTimeOffset>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("SourceCourseKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source_course_key");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id");

                    b.HasIndex("RawCollectionRunId")
                        .HasDatabaseName("ix_curated_racecourse_locations_raw_collection_run_id");

                    b.HasIndex("RawPayloadId")
                        .HasDatabaseName("ix_curated_racecourse_locations_raw_payload_id");

                    b.HasIndex("SourceSystem", "SourceCourseKey")
                        .IsUnique()
                        .HasDatabaseName("ux_curated_racecourse_locations_source_identity");

                    b.ToTable("racecourse_locations", "curated", t =>
                        {
                            t.HasCheckConstraint("ck_curated_racecourse_locations_latitude", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_curated_racecourse_locations_longitude", "longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Meeting", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Racecourse", "Racecourse")
                        .WithMany()
                        .HasForeignKey("RacecourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetings_racecourses_racecourse_id");

                    b.Navigation("Racecourse");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Race", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_races_meetings_meeting_id");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithOne("Result")
                        .HasForeignKey("HorseRacing.Domain.Entities.RaceResult", "RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_results_races_race_id");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Runner", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runners_horses_horse_id");

                    b.HasOne("HorseRacing.Domain.Entities.Jockey", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runners_jockeys_jockey_id");

                    b.HasOne("HorseRacing.Domain.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runners_owners_owner_id");

                    b.HasOne("HorseRacing.Domain.Entities.Race", "Race")
                        .WithMany("Runners")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runners_races_race_id");

                    b.HasOne("HorseRacing.Domain.Entities.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("StableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runners_stables_stable_id");

                    b.HasOne("HorseRacing.Domain.Entities.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runners_trainers_trainer_id");

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Owner");

                    b.Navigation("Race");

                    b.Navigation("Stable");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RunnerResult", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.RaceResult", "RaceResult")
                        .WithMany("RunnerResults")
                        .HasForeignKey("RaceResultId", "RaceId")
                        .HasPrincipalKey("Id", "RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runner_results_race_results_race_result_id");

                    b.HasOne("HorseRacing.Domain.Entities.Runner", "Runner")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.RunnerResult", "RunnerId", "RaceId")
                        .HasPrincipalKey("HorseRacing.Domain.Entities.Runner", "Id", "RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runner_results_runners_runner_id");

                    b.Navigation("RaceResult");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Trainer", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("StableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trainers_stables_stable_id");

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Curated.CuratedDomainObject", b =>
                {
                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Curated.CuratedPromotionRun", "LastPromotionRun")
                        .WithMany()
                        .HasForeignKey("LastPromotionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_domain_objects_promotion_runs_last_promotion_run_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", "RawCollectionRun")
                        .WithMany()
                        .HasForeignKey("RawCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_domain_objects_raw_collection_runs_raw_collection_run_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", "RawPayload")
                        .WithMany()
                        .HasForeignKey("RawPayloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_domain_objects_raw_payloads_raw_payload_id");

                    b.Navigation("LastPromotionRun");

                    b.Navigation("RawCollectionRun");

                    b.Navigation("RawPayload");
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Curated.CuratedPromotionRun", b =>
                {
                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", "RawCollectionRun")
                        .WithMany()
                        .HasForeignKey("RawCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_promotion_runs_raw_collection_runs_raw_collection_run_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", "RawPayload")
                        .WithMany()
                        .HasForeignKey("RawPayloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_promotion_runs_raw_payloads_raw_payload_id");

                    b.Navigation("RawCollectionRun");

                    b.Navigation("RawPayload");
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", b =>
                {
                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", "CollectionRun")
                        .WithOne("Payload")
                        .HasForeignKey("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", "CollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionRun");
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Weather.CuratedRaceWeather", b =>
                {
                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Curated.CuratedDomainObject", "CuratedRace")
                        .WithMany()
                        .HasForeignKey("CuratedRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_race_weather_domain_objects_curated_race_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Weather.CuratedRacecourseLocation", "RacecourseLocation")
                        .WithMany()
                        .HasForeignKey("RacecourseLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_race_weather_locations_racecourse_location_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", "RawCollectionRun")
                        .WithMany()
                        .HasForeignKey("RawCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_race_weather_raw_collection_runs_raw_collection_run_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", "RawPayload")
                        .WithMany()
                        .HasForeignKey("RawPayloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_race_weather_raw_payloads_raw_payload_id");

                    b.Navigation("CuratedRace");

                    b.Navigation("RacecourseLocation");

                    b.Navigation("RawCollectionRun");

                    b.Navigation("RawPayload");
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Weather.CuratedRacecourseLocation", b =>
                {
                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", "RawCollectionRun")
                        .WithMany()
                        .HasForeignKey("RawCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_racecourse_locations_raw_collection_runs_raw_collection_run_id");

                    b.HasOne("HorseRacing.Infrastructure.Ingestion.Raw.RawPayload", "RawPayload")
                        .WithMany()
                        .HasForeignKey("RawPayloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curated_racecourse_locations_raw_payloads_raw_payload_id");

                    b.Navigation("RawCollectionRun");

                    b.Navigation("RawPayload");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Race", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Runners");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.Navigation("RunnerResults");
                });

            modelBuilder.Entity("HorseRacing.Infrastructure.Ingestion.Raw.RawCollectionRun", b =>
                {
                    b.Navigation("Payload");
                });
#pragma warning restore 612, 618
        }
    }
}
